general:
  mode: "dedisperse"
  input_dir: "data"
  output_dir: "data"
  ephem: "/home/andrianovs/tempo2/T2runtime/ephemeris/DE405.1950.2050"
  verbose: 2

  t0: .3
  t1: 2.0


options:

  # "dedisperce" options
  ddtype: "incoherent"

  fold: true
  t2pred: "t2pred.dat"

  nchann: 16384
  mask: ""
  filter: true          # this only available for incoherent dedispersion
  tail_threshold: .7    # this only available for incoherent dedispersion
  std_threshold: 3      # this only available for incoherent dedispersion

  
advanced:
  fmax: 1260.0
  fmin: 1772.0
  sampling: 1024.0
  dm: 26.776

files:
  - rup106_bd_321-1252_ch07.vdif
