general:
  mode: "stream"
  input_dir: "data"
  output_dir: "data"
  parfile: "0329.par"
  site: "PO"
  verbose: 1
  buf_size: 2

  #t0: 0.0
  #t1: 5.0
  
  save_raw: false
  save_dyn: true
  save_sum: false



options:

  ddtype: "incoherent"

  #t2pred: "t2pred.dat"

  #nchann: 33554432
  nchann: 262144
  #nchann: 512

  bl_window: 100.0e-6
  threshold: 10.0

  filter: false
  tail_threshold: .0    
  std_threshold: 5.0
  max_len: 0

  
# Owerwrite files' headers
advanced:
  sampling: 1024.0
  #dm: 26.776
  #fmin: 1772.0
  #fmax: 1260.0
  fmin: 2675.8
  fmax: 2163.8
  dm: 56.7712

files:
  #- 010818_0329+54_00adc
  - Crab_pulse/r6326e_sw_326-1702_ch01.vdif_7195.vdif
  #- Crab_pulse/r6326e_zv_326-1702_ch01.vdif_7194.vdif
  #- Crab_pulse/r6326e_bv_326-1702_ch01.vdif_7183.vdif

