general:
  mode: "dedisperse"
  input_dir: "data"
  output_dir: "data"
  parfile: "0329.par"
  site: "PO"
  verbose: 2

  #t0: 0.3
  #t1: 20


options:

  # "dedisperce" options
  ddtype: "coherent"

  fold: false
  #t2pred: "t2pred.dat"

  nchann: 4194304
  #nchann: 512
  mask: ""
  filter: true          # this only available for incoherent dedispersion
  tail_threshold: .7    # this only available for incoherent dedispersion
  std_threshold: 3      # this only available for incoherent dedispersion

  
advanced:
  #fmax: 1260.0
  #fmin: 1772.0
  #sampling: 1024.0

files:
  - 010818_0329+54_00adc
#  - 020818_0329+54_00adc
#  - 011022_1133+16_00adc
#  - 011222_1133+16_00adc
#  - 220621_0531+21_00adc
