general:
  mode: "search"
  input_dir: "data"
  output_dir: "data"
  parfile: "0329.par"
  site: "PO"
  verbose: 1
  buf_size: 10

  #t0: 17.5
  #t1: 20.0
  
  save_raw: false
  save_dyn: false
  save_sum: true



options:

  ddtype: "incoherent"

  #t2pred: "t2pred.dat"

  #nchann: 33554432
  nchann: 2048
  #nchann: 512
  mask: ""              # External file containing mask. Has higher priority than the filtration
  filter: true
  tail_threshold: .5    
  std_threshold: 3.0
  max_len: 0

  
# Owerwrite files' headers
advanced:
  sampling: 1024.0
  #dm: 26.776
  #fmin: 1772.0
  #fmax: 1260.0
  fmin: 2675.8
  fmax: 2163.8
  dm: 56.7712

files:
   - Crab_pulse/r6326e_bv_326-1702_ch01.vdif_7183.vdif 
#  - wideband_1024_2048.vdif
#  - rup106_bd_321-1252_ch07.vdif
#  - 010818_0329+54_00adc
#  - 020818_0329+54_00adc
#  - 011022_1133+16_00adc
#  - 011222_1133+16_00adc
#  - 220621_0531+21_00adc
