general:
  mode: "stream"
  input_dir: "data"
  output_dir: "data"
  parfile: "0329.par"
  site: "PO"
  verbose: 1
  buf_size: 10

  t0: 479.0
  t1: 480.0
  
  save_raw: true
  save_dyn: false
  save_sum: false



options:

  ddtype: "incoherent"

  #t2pred: "t2pred.dat"

  #nchann: 33554432
  nchann: 2048
  #nchann: 512

  bl_window: 100.0e-6
  threshold: 20.0

  filter: true
  tail_threshold: .5    
  std_threshold: 3.0
  max_len: 1000

  
# Owerwrite files' headers
advanced:
  sampling: 1024.0
  #dm: 26.776
  #fmin: 1772.0
  #fmax: 1260.0
  fmin: 2675.8
  fmax: 2163.8
  dm: 56.7712

files:
  - rup103_bv_055-0550_ch01.vdif
  #- rup103_bv_055-0612_ch01.vdif_147601.vdif
